### ISSUE TITLE
upgrade to w_transport 2.0.1

### ISSUE THREAD

**Issue by johnryan-wf** [Workiva/w_service#69]
https://github.com/Workiva/w_transport/releases

**Comment by johnryan-wf** [comment]
FYI @evanweible-wf

**Comment by johnryan-wf** [comment]
```
golinking example
Uncaught Unhandled exception:
'package:messaging_sdk/src/public/options.dart': malformed type: line 20 pos 9: cannot resolve class 'wt.Client' from 'Options'
  final wt.Client client;
        ^
type 'HttpProvider' is not a subtype of type 'malformed' of 'client'.
#0      Options.Options (package:messaging_sdk/src/public/options.dart:26:49)
#1      HtmlWdeskSession.provideMessagingClient.<provideMessagingClient_async_body> (package:w_linking_client/src/wdesk_session/html_wdesk_session.dart:54:37)
#2      _RootZone.runUnary (dart:async/zone.dart:1149)
```

**Comment by johnryan-wf** [comment]
deps: 

```
|-- w_linking_client 0.3.3
|   |-- directory_thrift 0.0.1
|   |   |-- linking_thrift...
|   |   |-- thrift...
|   |   '-- workiva_thrift...
|   |-- frugal...
|   |-- http...
|   |-- linking_thrift 0.0.1
|   |   |-- frugal...
|   |   |-- thrift...
|   |   '-- workiva_thrift 0.0.1
|   |       '-- thrift...
|   |-- logging...
|   |-- messaging_sdk...
|   |-- quiver...
|   |-- thrift...
|   |-- uuid...
|   |-- vessel...
|   |-- w_oauth2...
|   |-- w_service 1.0.2
|   |   |-- fluri 1.1.0
|   |   '-- w_transport 1.0.1
|   |       '-- fluri...
|   '-- w_session 1.2.2
|       |-- fluri...
|       |-- state_machine...
|       |-- w_service...
|       '-- w_transport...
```

**Comment by evanweible-wf** [comment]
@johnryan-wf Once w_transport 2.1.0 is out, w_service will no longer be necessary. You'll use a `Client` instead of a `HttpProvider`.

**Comment by johnryan-wf** [comment]
so w_linking_client 0.3.3 should use 2.1.0?

**Comment by johnryan-wf** [comment]
can I just target master for now?

**Comment by johnryan-wf** [comment]
it's getting a little hairy to try to take out w_service, since messaging_frontent, messaging_sdk, and w_oauth2 all depend on `^1.0.2`

**Comment by johnryan-wf** [comment]
discussed IRL: going to use dependency overrides for now
